# .streamlit/secrets.toml

[app]
# name = "CompanyName"
# icon = "🤘"

[llm]
provider = "openai"  # Options: openai, anthropic, local

[openai]
api_key = "----"
model = "gpt-4o-mini"

# [anthropic]
# api_key = "----"
# model = "claude-3-5-sonnet-20240620"

# [local]
# base_url = "http://localhost:1234/v1"

